<a href="https://colab.research.google.com/github/celacarney/Linear-Algebra-Projects/blob/main/Gram_Schmidt_Process_from_Scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [14]:
# Create a vector:
r1 = np.array([3, 0, 3, 0])
r1

array([3, 0, 3, 0])

In [8]:
# Vector arithmetic:
3*r1

array([9, 0, 9, 0])

In [10]:
# Dot product:
r1.dot(r1)

18

In [13]:
# Square root / magnitude of the vector:
np.sqrt(r1.dot(r1))

4.242640687119285

#**Gram- Schmidt Orthonormalization Process**

We'll use the Gram-Schmidt process to find orthogonal vectors in $R^4$


##Our "Random" Vectors:

In [32]:
r1 = np.array([3, 0, 3, 0])
r2 = np.array([3, 2, 3, 3])
r3 = np.array([-7, -4, -5, -6])
r4 = np.array([-7, -3, -11, 2])

##Process $r_1$

In [33]:
# Choose the messy vector and subtract off the "nice" orthogonal pieces:
t1 = r1
#t1

# Find the size of t1:
m = np.sqrt(t1.dot(t1))

# Create the nice orthonormal vector u1:
u1 = (1/m) * t1
u1

array([0.70710678, 0.        , 0.70710678, 0.        ])

In [38]:
# Let's check magnitude and orthogonal:
u1.dot(u1)

1.0000000000000002

##Process $r_2$

In [34]:
# Choose the messy vector and subtract off the "nice" orthogonal pieces:
t2 = r2 - (u1.dot(r2))*u1
#t2

# Find the size of t2:
m = np.sqrt(t2.dot(t2))
m

# Create the nice orthonormal vector u2:
u2 = (1/m) * t2
u2

# essentially: [0, .55, 0, .83]
# should be: [0, 2/sqrt(13), 0, 3/sqrt(13)]

array([-1.23168186e-16,  5.54700196e-01, -1.23168186e-16,  8.32050294e-01])

In [45]:
# Lets check the magnitude and orthogonal:
print("the size of u2: ",(u2.dot(u2)));
print("u2 dotted with u1 : ",(u2.dot(u1)))

the size of u2:  1.0
u2 dotted with u1 :  -1.741861189847285e-16


##Process $r_3$

In [35]:
# Choose the messy vector and subtract off the "nice" orthogonal pieces:
t3 = r3 - (u1.dot(r3))*u1 - (u2.dot(r3))*u2
#t3

# Find the size of t2:
m = np.sqrt(t3.dot(t3))
m

# Create the nice orthonormal vector u2:
u3 = (1/m) * t3
u3


array([-7.07106781e-01, -3.14018492e-16,  7.07106781e-01, -6.28036983e-16])

##Process $r_4$

In [37]:
# Choose the messy vector and subtract off the "nice" orthogonal pieces:
t4 = r4 - (u1.dot(r4))*u1 - (u2.dot(r4))*u2 - (u3.dot(r4))*u3
#t4

# Find the size of t2:
m = np.sqrt(t4.dot(t4))
m

# Create the nice orthonormal vector u2:
u4 = (1/m) * t4
u4

array([ 0.        , -0.83205029,  0.        ,  0.5547002 ])

#Sanity Checks:

Vectors should be orthogonal and have size 1:

In [ ]:
print("r1 = ")
print()